name: weread sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: weread sync
        run: |
          python scripts/weread.py "${{secrets.WEREAD_COOKIE}}" "${{secrets.NOTION_TOKEN}}" "${{secrets.NOTION_DATABASE_ID}}" "${{ github.ref }}" "${{ github.repository }}" --styles 0 1 2 --colors 0 1 2 3 4 5
      - name: weread heatmap
        run: |
          github_heatmap weread  --weread_cookie "pgv_pvid=359285752; RK=FhwgTWxPUP; pac_uid=1_1574845183; ptcz=d8a6cd0df7f250f9303b82c134691bd39fcc3e344c0f49cd2e7eef6a9a2b8be5; pgv_pvi=5151840256; tvfe_boss_uuid=85b337d94e73bb7e; fqm_pvqid=5e4d44ee-8907-4999-8bab-c2884347f92f; iip=0; wr_gid=287825284; wr_theme=white; _qimei_uuid42=17b0f15200410001faf05f9d22c368302a59faf56a; _qimei_q36=; _qimei_h38=fe339459faf05f9d22c368300200000fa17b0f; suid=ek169554546252152417; wr_vid=11249088; wr_pf=0; wr_rt=web%40V5cvet_Xx2ydfn4YZO~_AL; wr_localvid=1fc324606aba5c01fc8f171; wr_name=turnaround; wr_gender=2; wr_avatar=https%3A%2F%2Fthirdwx.qlogo.cn%2Fmmopen%2Fvi_32%2FWYAicvY5hVaDC4KwaARLu7iaicOLMEJLrYT67QXz6gvpOSC1BqjZsUZd6UDHp5Fnra1xbkmVXCoWecNGdTa5G4x4A%2F132; wr_fp=1358298738; qq_domain_video_guid_verify=42e41a67e4d2ed42; _qimei_fingerprint=a2523ff0d4638be3ce2784f1854ea4f2; wr_skey=dcUYD9f6" --year $(date +"%Y") --me "${{secrets.NAME}}" --with-animation --background-color=${{ vars.background_color||'#FFFFFF'}} --track-color=${{ vars.track_color||'#ACE7AE'}} --special-color1=${{ vars.special_color||'#69C16E'}} --special-color2=${{ vars.special_color2||'#549F57'}} --dom-color=${{ vars.dom_color||'#EBEDF0'}} --text-color=${{ vars.text_color||'#000000'}}
      - name: push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m 'add new cover' || echo "nothing to commit"
          git push || echo "nothing to push"
